/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fr.lnl.game.client;

import fr.lnl.game.server.MessageUtils;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class MessageUtilsTest {
    @Test
    public void testGetMessage() {
        assertEquals("Hello World!", MessageUtils.getMessage());
    }
}
