/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fr.lnl.game.client;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

import static fr.lnl.game.server.MessageUtils.getMessage;

public class App extends Application {

    public static void main(String[] args) {
        String result = getMessage();
        System.out.println(result);
        launch();
    }

    @Override
    public void start(Stage stage) throws Exception {
        System.out.println("Launching stage");
        String javaVersion = System.getProperty("java.version");
        String javafxVersion = System.getProperty("javafx.version");
        Label l = new Label("Hello, JavaFX version " + javafxVersion + ", running on Java " + javaVersion + ".");
        Scene scene = new Scene(new StackPane(l), 640, 480);
        stage.setScene(scene);
        stage.show();
    }
}
